steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy', 'CleanupExpiredManifest',
      '--runtime', 'go111',
      '--trigger-topic', 'cleanupExpiredManifest',
      '--source', '.',
      '--memory', '128MB',
      '--region', 'us-central1',
      '--timeout', '60s'
    ]
